### ISSUE TITLE
errors upon launching

### ISSUE THREAD

**Issue by dasfalco** [noggaholic/machinima-studio#16]
![electron_nynyri2oz2](https://user-images.githubusercontent.com/32146805/53145785-e042ed00-35a1-11e9-86bb-ffee8092365c.png)
Issue is what can be seen in screenshot above ,how do i proceed ?

**Comment by karliky** [comment]
Solved with the latest release https://github.com/noggaholic/machinima-studio/releases/tag/2.0

**Comment by Ambreon1** [comment]
![ооо](https://github.com/noggaholic/machinima-studio/assets/142913982/ba19169d-be1f-494c-9315-2888db1662ab)
Long starting

**Comment by dasfalco** [comment]
This app no longer works because the offsets arent updated anymore and on top of that it wasnt never built to support dx11 .Sadly this project is discontinued
________________________________
Van: Пронин Вячеслав ***@***.***>
Verzonden: dinsdag 25 juni 2024 10:22
Aan: noggaholic/machinima-studio ***@***.***>
CC: dasfalco ***@***.***>; Author ***@***.***>
Onderwerp: Re: [noggaholic/machinima-studio] errors upon launching (#16)


default.PNG (view on web)<https://github.com/noggaholic/machinima-studio/assets/142913982/ba19169d-be1f-494c-9315-2888db1662ab>
Long starting

**Comment by nightlark** [comment]
I haven't looked at this in a long time, but from what I recall it's rendering in a separate window that goes on top of the GW2 one, so dx11 isn't an issue from a UI rendering perspective. If someone felt inclined to get it working again, the place to start would be going through the patterns and offsets in https://github.com/noggaholic/machinima-studio/blob/master/src/gw2/src/offsets.js and just figure out which ones are no longer valid for the latest GW2 version.

Given the 5 years since the previous update, it's possible that could be a very large list of broken patterns. Ones that are closely tied to the dx9 renderer might be particularly tricky, though there are other parts of GW2 that could have been refactored and could be hard to find new patterns for.

**Comment by karliky** [comment]
The app was compatible with the x86 binary of GW2 and not x64 so it's not only a thing about offsets but also about the target architecture
